/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAdministracaoRouteImport } from './routes/_app.administracao'
import { Route as AppAuditoriaRouteImport } from './routes/_app.auditoria'
import { Route as AppGargalosRouteImport } from './routes/_app.gargalos'
import { Route as AppLimparDocumentoRouteImport } from './routes/_app.limpar-documento'
import { Route as AppNeoDashboardRouteImport } from './routes/_app.neo.dashboard'
import { Route as AppNeoRegistrosRouteImport } from './routes/_app.neo.registros'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministracaoRoute = AppAdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppGargalosRoute = AppGargalosRouteImport.update({
  id: '/gargalos',
  path: '/gargalos',
  getParentRoute: () => AppRoute,
} as any)
const AppLimparDocumentoRoute = AppLimparDocumentoRouteImport.update({
  id: '/limpar-documento',
  path: '/limpar-documento',
  getParentRoute: () => AppRoute,
} as any)
const AppNeoDashboardRoute = AppNeoDashboardRouteImport.update({
  id: '/neo/dashboard',
  path: '/neo/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNeoRegistrosRoute = AppNeoRegistrosRouteImport.update({
  id: '/neo/registros',
  path: '/neo/registros',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/administracao': typeof AppAdministracaoRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/gargalos': typeof AppGargalosRoute
  '/limpar-documento': typeof AppLimparDocumentoRoute
  '/neo/dashboard': typeof AppNeoDashboardRoute
  '/neo/registros': typeof AppNeoRegistrosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/administracao': typeof AppAdministracaoRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/gargalos': typeof AppGargalosRoute
  '/limpar-documento': typeof AppLimparDocumentoRoute
  '/': typeof AppIndexRoute
  '/neo/dashboard': typeof AppNeoDashboardRoute
  '/neo/registros': typeof AppNeoRegistrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/administracao': typeof AppAdministracaoRoute
  '/_app/auditoria': typeof AppAuditoriaRoute
  '/_app/gargalos': typeof AppGargalosRoute
  '/_app/limpar-documento': typeof AppLimparDocumentoRoute
  '/_app/': typeof AppIndexRoute
  '/_app/neo/dashboard': typeof AppNeoDashboardRoute
  '/_app/neo/registros': typeof AppNeoRegistrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/administracao'
    | '/auditoria'
    | '/gargalos'
    | '/limpar-documento'
    | '/neo/dashboard'
    | '/neo/registros'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/administracao'
    | '/auditoria'
    | '/gargalos'
    | '/limpar-documento'
    | '/'
    | '/neo/dashboard'
    | '/neo/registros'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/administracao'
    | '/_app/auditoria'
    | '/_app/gargalos'
    | '/_app/limpar-documento'
    | '/_app/'
    | '/_app/neo/dashboard'
    | '/_app/neo/registros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administracao': {
      id: '/_app/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AppAdministracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auditoria': {
      id: '/_app/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gargalos': {
      id: '/_app/gargalos'
      path: '/gargalos'
      fullPath: '/gargalos'
      preLoaderRoute: typeof AppGargalosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/limpar-documento': {
      id: '/_app/limpar-documento'
      path: '/limpar-documento'
      fullPath: '/limpar-documento'
      preLoaderRoute: typeof AppLimparDocumentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/neo/dashboard': {
      id: '/_app/neo/dashboard'
      path: '/neo/dashboard'
      fullPath: '/neo/dashboard'
      preLoaderRoute: typeof AppNeoDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/neo/registros': {
      id: '/_app/neo/registros'
      path: '/neo/registros'
      fullPath: '/neo/registros'
      preLoaderRoute: typeof AppNeoRegistrosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdministracaoRoute: typeof AppAdministracaoRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppGargalosRoute: typeof AppGargalosRoute
  AppLimparDocumentoRoute: typeof AppLimparDocumentoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNeoDashboardRoute: typeof AppNeoDashboardRoute
  AppNeoRegistrosRoute: typeof AppNeoRegistrosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdministracaoRoute: AppAdministracaoRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppGargalosRoute: AppGargalosRoute,
  AppLimparDocumentoRoute: AppLimparDocumentoRoute,
  AppIndexRoute: AppIndexRoute,
  AppNeoDashboardRoute: AppNeoDashboardRoute,
  AppNeoRegistrosRoute: AppNeoRegistrosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
